// generated by stringer -type=jpTokType; DO NOT EDIT

package path

import "fmt"

const _tokType_name = "jpTUnknownjpTStarjpTDotjpTFilterjpTFlattenjpTLparenjpTRparenjpTLbracketjpTRbracketjpTLbracejpTRbracejpTOrjpTPipejpTNumberjpTUnquotedIdentifierjpTQuotedIdentifierjpTCommajpTColonjpTLTjpTLTEjpTGTjpTGTEjpTEQjpTNEjpTJSONLiteraljpTStringLiteraljpTCurrentjpTExprefjpTAndjpTNotjpTEOF"

var _tokType_index = [...]uint16{0, 10, 17, 23, 32, 42, 51, 60, 71, 82, 91, 100, 105, 112, 121, 142, 161, 169, 177, 182, 188, 193, 199, 204, 209, 223, 239, 249, 258, 264, 270, 276}

func (i jpTokType) String() string {
	if i < 0 || i >= jpTokType(len(_tokType_index)-1) {
		return fmt.Sprintf("jpTokType(%d)", i)
	}
	return _tokType_name[_tokType_index[i]:_tokType_index[i+1]]
}
