version: "3"

tasks:
  test:
    desc: Run all Go tests.
    cmds:
      - go test ./...

  test:race:
    desc: Run Go tests with the race detector.
    cmds:
      - go test -race ./...

  bench:
    desc: Run all Go benchmarks.
    cmds:
      - go test -bench . -benchmem -run=^$ ./...

  bench:path:
    desc: Run TRON path (JMESPath-style) benchmarks.
    cmds:
      - go test -bench BenchmarkJMESPath -benchmem -run=^$ ./path

  bench:save:
    desc: Run all benchmarks and save output.
    vars:
      NAME: "{{.NAME | default \"latest\"}}"
    cmds:
      - go test -bench . -benchmem -run=^$ ./... | tee "bench_{{.NAME}}.txt"

  bench:path:save:
    desc: Run path benchmarks and save output.
    vars:
      NAME: "{{.NAME | default \"latest\"}}"
    cmds:
      - go test -bench BenchmarkJMESPath -benchmem -run=^$ ./path | tee "bench_path_{{.NAME}}.txt"

  benchstat:
    desc: Compare two benchmark files with benchstat.
    vars:
      OLD: "{{.OLD}}"
      NEW: "{{.NEW}}"
    cmds:
      - benchstat "{{.OLD}}" "{{.NEW}}"

  benchstat:latest:
    desc: Compare two saved benchmark files in the Go dir.
    vars:
      OLD: "{{.OLD | default \"bench_full_run1.txt\"}}"
      NEW: "{{.NEW | default \"bench_full_run2.txt\"}}"
    cmds:
      - benchstat "{{.OLD}}" "{{.NEW}}"

  benchstat:install:
    desc: Install benchstat.
    cmds:
      - go install golang.org/x/perf/cmd/benchstat@latest

  fuzz:
    desc: Run Go fuzz tests (defaults to all fuzzers for 10s).
    vars:
      NAME: "{{.NAME | default \"Fuzz\"}}"
      TIME: "{{.TIME | default \"10s\"}}"
      PKG: "{{.PKG | default \"./...\"}}"
    cmds:
      - go test -run=^$ -fuzz "{{.NAME}}" -fuzztime "{{.TIME}}" "{{.PKG}}"

  trongen:build:
    desc: Build the trongen generator binary.
    cmds:
      - mkdir -p ./bin
      - go build -o ./bin/trongen ./cmd/trongen

  trongen:install:
    desc: Install the trongen generator binary.
    cmds:
      - go install ./cmd/trongen

  trongen:example:
    desc: Generate trongen output for the example package.
    cmds:
      - go run ./cmd/trongen --dir ./examples/trongen/basic
