// Code generated by trongen; DO NOT EDIT.

package basic

import (
	"github.com/starfederation/tron-go"
)

func AddressFromTRON(doc []byte) (*AddressTRON, error) {
	if len(doc) == 0 {
		return nil, trongenProxyErrNoData
	}
	root, err := trongenProxyMapRoot(doc)
	if err != nil {
		return nil, err
	}
	return &AddressTRON{doc: doc, root: root}, nil
}

// AddressTRON lazily converts between TRON documents and Address.
type AddressTRON struct {
	doc  []byte
	root uint32
}

func (v *Address) FullCopyToTRON() (*AddressTRON, error) {
	doc, err := trongenProxyMarshal(v)
	if err != nil {
		return nil, err
	}
	return AddressFromTRON(doc)
}

func (t *AddressTRON) FullCopyToAddress(out *Address) error {
	if len(t.doc) == 0 {
		return trongenProxyErrNoData
	}
	doc, err := trongenProxyDocForRoot(t.doc, t.root)
	if err != nil {
		return err
	}
	return trongenProxyUnmarshal(doc, out)
}

func (t *AddressTRON) Line1() (string, bool, error) {
	var out string
	if len(t.doc) == 0 {
		return out, false, trongenProxyErrNoData
	}
	val, ok, err := trongenProxyGetFieldValue(t.doc, t.root, "line1", 0xd7ecd202)
	if err != nil || !ok {
		return out, ok, err
	}
	if err := trongenProxyUnmarshalValue(t.doc, val, &out); err != nil {
		return out, false, err
	}
	return out, true, nil
}

func (t *AddressTRON) SetLine1(v string) error {
	doc, root, err := trongenProxySetFieldValue(t.doc, t.root, "line1", 0xd7ecd202, v)
	if err != nil {
		return err
	}
	t.doc = doc
	t.root = root
	return nil
}

func (t *AddressTRON) City() (string, bool, error) {
	var out string
	if len(t.doc) == 0 {
		return out, false, trongenProxyErrNoData
	}
	val, ok, err := trongenProxyGetFieldValue(t.doc, t.root, "city", 0xae3b0773)
	if err != nil || !ok {
		return out, ok, err
	}
	if err := trongenProxyUnmarshalValue(t.doc, val, &out); err != nil {
		return out, false, err
	}
	return out, true, nil
}

func (t *AddressTRON) SetCity(v string) error {
	doc, root, err := trongenProxySetFieldValue(t.doc, t.root, "city", 0xae3b0773, v)
	if err != nil {
		return err
	}
	t.doc = doc
	t.root = root
	return nil
}

func (t *AddressTRON) State() (string, bool, error) {
	var out string
	if len(t.doc) == 0 {
		return out, false, trongenProxyErrNoData
	}
	val, ok, err := trongenProxyGetFieldValue(t.doc, t.root, "state", 0xa13aa025)
	if err != nil || !ok {
		return out, ok, err
	}
	if err := trongenProxyUnmarshalValue(t.doc, val, &out); err != nil {
		return out, false, err
	}
	return out, true, nil
}

func (t *AddressTRON) SetState(v string) error {
	doc, root, err := trongenProxySetFieldValue(t.doc, t.root, "state", 0xa13aa025, v)
	if err != nil {
		return err
	}
	t.doc = doc
	t.root = root
	return nil
}

func (t *AddressTRON) Zip() (string, bool, error) {
	var out string
	if len(t.doc) == 0 {
		return out, false, trongenProxyErrNoData
	}
	val, ok, err := trongenProxyGetFieldValue(t.doc, t.root, "zip", 0x6c859798)
	if err != nil || !ok {
		return out, ok, err
	}
	if err := trongenProxyUnmarshalValue(t.doc, val, &out); err != nil {
		return out, false, err
	}
	return out, true, nil
}

func (t *AddressTRON) SetZip(v string) error {
	doc, root, err := trongenProxySetFieldValue(t.doc, t.root, "zip", 0x6c859798, v)
	if err != nil {
		return err
	}
	t.doc = doc
	t.root = root
	return nil
}

func (t *AddressTRON) TRON() ([]byte, error) {
	if len(t.doc) == 0 {
		return nil, trongenProxyErrNoData
	}
	return trongenProxyDocForRoot(t.doc, t.root)
}

func (t *AddressTRON) Raw() []byte {
	return t.doc
}

func UserFromTRON(doc []byte) (*UserTRON, error) {
	if len(doc) == 0 {
		return nil, trongenProxyErrNoData
	}
	root, err := trongenProxyMapRoot(doc)
	if err != nil {
		return nil, err
	}
	return &UserTRON{doc: doc, root: root}, nil
}

// UserTRON lazily converts between TRON documents and User.
type UserTRON struct {
	doc  []byte
	root uint32
}

func (v *User) FullCopyToTRON() (*UserTRON, error) {
	doc, err := trongenProxyMarshal(v)
	if err != nil {
		return nil, err
	}
	return UserFromTRON(doc)
}

func (t *UserTRON) FullCopyToUser(out *User) error {
	if len(t.doc) == 0 {
		return trongenProxyErrNoData
	}
	doc, err := trongenProxyDocForRoot(t.doc, t.root)
	if err != nil {
		return err
	}
	return trongenProxyUnmarshal(doc, out)
}

func (t *UserTRON) ID() (string, bool, error) {
	var out string
	if len(t.doc) == 0 {
		return out, false, trongenProxyErrNoData
	}
	val, ok, err := trongenProxyGetFieldValue(t.doc, t.root, "id", 0xe9ca40df)
	if err != nil || !ok {
		return out, ok, err
	}
	if err := trongenProxyUnmarshalValue(t.doc, val, &out); err != nil {
		return out, false, err
	}
	return out, true, nil
}

func (t *UserTRON) SetID(v string) error {
	doc, root, err := trongenProxySetFieldValue(t.doc, t.root, "id", 0xe9ca40df, v)
	if err != nil {
		return err
	}
	t.doc = doc
	t.root = root
	return nil
}

func (t *UserTRON) Name() (string, bool, error) {
	var out string
	if len(t.doc) == 0 {
		return out, false, trongenProxyErrNoData
	}
	val, ok, err := trongenProxyGetFieldValue(t.doc, t.root, "name", 0xcc0bc31f)
	if err != nil || !ok {
		return out, ok, err
	}
	if err := trongenProxyUnmarshalValue(t.doc, val, &out); err != nil {
		return out, false, err
	}
	return out, true, nil
}

func (t *UserTRON) SetName(v string) error {
	doc, root, err := trongenProxySetFieldValue(t.doc, t.root, "name", 0xcc0bc31f, v)
	if err != nil {
		return err
	}
	t.doc = doc
	t.root = root
	return nil
}

func (t *UserTRON) Email() (string, bool, error) {
	var out string
	if len(t.doc) == 0 {
		return out, false, trongenProxyErrNoData
	}
	val, ok, err := trongenProxyGetFieldValue(t.doc, t.root, "email", 0x29ff2c6d)
	if err != nil || !ok {
		return out, ok, err
	}
	if err := trongenProxyUnmarshalValue(t.doc, val, &out); err != nil {
		return out, false, err
	}
	return out, true, nil
}

func (t *UserTRON) SetEmail(v string) error {
	doc, root, err := trongenProxySetFieldValue(t.doc, t.root, "email", 0x29ff2c6d, v)
	if err != nil {
		return err
	}
	t.doc = doc
	t.root = root
	return nil
}

func (t *UserTRON) Address() (*AddressTRON, bool, error) {
	var out *AddressTRON
	if len(t.doc) == 0 {
		return out, false, trongenProxyErrNoData
	}
	val, ok, err := trongenProxyGetFieldValue(t.doc, t.root, "address", 0x22ffcdb1)
	if err != nil || !ok {
		return out, ok, err
	}
	if val.Type != tron.TypeMap {
		return out, false, trongenProxyErrFieldNotMap
	}
	out = &AddressTRON{doc: t.doc, root: val.Offset}
	return out, true, nil
}

func (t *UserTRON) SetAddress(v Address) error {
	doc, root, err := trongenProxySetFieldValue(t.doc, t.root, "address", 0x22ffcdb1, v)
	if err != nil {
		return err
	}
	t.doc = doc
	t.root = root
	return nil
}

func (t *UserTRON) Tags() ([]string, bool, error) {
	var out []string
	if len(t.doc) == 0 {
		return out, false, trongenProxyErrNoData
	}
	val, ok, err := trongenProxyGetFieldValue(t.doc, t.root, "tags", 0x09bb222d)
	if err != nil || !ok {
		return out, ok, err
	}
	if err := trongenProxyUnmarshalValue(t.doc, val, &out); err != nil {
		return out, false, err
	}
	return out, true, nil
}

func (t *UserTRON) SetTags(v ...string) error {
	doc, root, err := trongenProxySetFieldValue(t.doc, t.root, "tags", 0x09bb222d, v)
	if err != nil {
		return err
	}
	t.doc = doc
	t.root = root
	return nil
}

func (t *UserTRON) TRON() ([]byte, error) {
	if len(t.doc) == 0 {
		return nil, trongenProxyErrNoData
	}
	return trongenProxyDocForRoot(t.doc, t.root)
}

func (t *UserTRON) Raw() []byte {
	return t.doc
}

var (
	trongenProxyErrNoData      = tron.ErrTronProxyNoData
	trongenProxyErrFieldNotMap = tron.ErrTronProxyFieldNotMap
)

func trongenProxyMapRoot(doc []byte) (uint32, error) {
	return tron.MapRoot(doc)
}

func trongenProxyDocForRoot(doc []byte, root uint32) ([]byte, error) {
	return tron.DocForRoot(doc, root)
}

func trongenProxyGetFieldValue(doc []byte, root uint32, key string, hash uint32) (tron.Value, bool, error) {
	return tron.GetFieldValue(doc, root, key, hash)
}

func trongenProxySetFieldValue(doc []byte, root uint32, key string, hash uint32, value any) ([]byte, uint32, error) {
	return tron.SetFieldValue(doc, root, key, hash, value)
}

func trongenProxyMarshal(v any) ([]byte, error) {
	return tron.Marshal(v)
}

func trongenProxyUnmarshal(doc []byte, out any) error {
	return tron.Unmarshal(doc, out)
}

func trongenProxyUnmarshalValue(doc []byte, v tron.Value, out any) error {
	return tron.UnmarshalValue(doc, v, out)
}
