// Code generated by trongen; DO NOT EDIT.

package jsonschema

import (
	"encoding/json"
	"errors"
	"github.com/starfederation/tron-go"
)

var errTronProxyNoData = errors.New("trongen: no data")

// FlagOutputTRON lazily converts between TRON documents and FlagOutput.
type FlagOutputTRON struct {
	doc   []byte
	value *FlagOutput
}

func (t *FlagOutputTRON) FromTRON(doc []byte) {
	t.doc = doc
	t.value = nil
}

func (t *FlagOutputTRON) FromValue(v *FlagOutput) {
	t.value = v
	t.doc = nil
}

func (t *FlagOutputTRON) Value() (*FlagOutput, error) {
	if t.value != nil {
		return t.value, nil
	}
	if len(t.doc) == 0 {
		return nil, errTronProxyNoData
	}
	jsonText, err := tron.ToJSON(t.doc)
	if err != nil {
		return nil, err
	}
	var v FlagOutput
	if err := json.Unmarshal([]byte(jsonText), &v); err != nil {
		return nil, err
	}
	t.value = &v
	t.doc = nil
	return t.value, nil
}

func (t *FlagOutputTRON) TRON() ([]byte, error) {
	if len(t.doc) != 0 {
		return t.doc, nil
	}
	if t.value == nil {
		return nil, errTronProxyNoData
	}
	data, err := json.Marshal(t.value)
	if err != nil {
		return nil, err
	}
	doc, err := tron.FromJSON(data)
	if err != nil {
		return nil, err
	}
	t.doc = doc
	return t.doc, nil
}

func (t *FlagOutputTRON) Raw() []byte {
	return t.doc
}

// OutputUnitTRON lazily converts between TRON documents and OutputUnit.
type OutputUnitTRON struct {
	doc   []byte
	value *OutputUnit
}

func (t *OutputUnitTRON) FromTRON(doc []byte) {
	t.doc = doc
	t.value = nil
}

func (t *OutputUnitTRON) FromValue(v *OutputUnit) {
	t.value = v
	t.doc = nil
}

func (t *OutputUnitTRON) Value() (*OutputUnit, error) {
	if t.value != nil {
		return t.value, nil
	}
	if len(t.doc) == 0 {
		return nil, errTronProxyNoData
	}
	jsonText, err := tron.ToJSON(t.doc)
	if err != nil {
		return nil, err
	}
	var v OutputUnit
	if err := json.Unmarshal([]byte(jsonText), &v); err != nil {
		return nil, err
	}
	t.value = &v
	t.doc = nil
	return t.value, nil
}

func (t *OutputUnitTRON) TRON() ([]byte, error) {
	if len(t.doc) != 0 {
		return t.doc, nil
	}
	if t.value == nil {
		return nil, errTronProxyNoData
	}
	data, err := json.Marshal(t.value)
	if err != nil {
		return nil, err
	}
	doc, err := tron.FromJSON(data)
	if err != nil {
		return nil, err
	}
	t.doc = doc
	return t.doc, nil
}

func (t *OutputUnitTRON) Raw() []byte {
	return t.doc
}
